### ISSUE TITLE
Experiments are not accessable

### ISSUE THREAD

**Issue by madhavipuliraju** [vlabs-on-openedx/open-edx-mechanical-laboratory-experience-in-fluid-and-thermal-sciences-iitg#1]
Experiments are not accessable. All experiments are pointng to 202.141.81.60 ip address

**Comment by sravanthimodepu** [comment]
The lab is hosted in the cloud, but the simulations are running from their institute server(202.141.81.60). So we cannot access the simulations.

**Comment by sravanthimodepu** [comment]
Closing the issue.
